[package]
name = "snow-owl-tftp"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
snow-owl-core = { path = "../snow-owl-core" }
tokio.workspace = true
tokio-util.workspace = true
bytes.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
